import React from 'react';
import Navigation1 from '../components/watermelon/Navigation1.jsx';
import {Footer} from '../components/BusinessAndContact.jsx';
import TextHoverEffectDemo from '../../components/text-hover-effect-demo.tsx';
import {Arrow} from '../components/Primitives.jsx';
import CatalogueImage from '../components/CatalogueImage.jsx';
import {company,contacts} from '../data/company.js';
import {categories,categoryUrl} from '../catalogue/model.js';
import {selectCategoryFeature} from '../catalogue/categoryFeatured.js';
import {categoryTone} from '../catalogue/CategoryPresentation.jsx';
import EnquiryPreparation from './EnquiryPreparation.jsx';
import useBusinessMetadata from './useBusinessMetadata.js';
import './business.css';

function BusinessCategory({category}){const feature=selectCategoryFeature(category);return <a className="business-category" href={categoryUrl(category)} data-tone={categoryTone(category)}><div className="business-category-stage">{feature.imageKey?<div className="media-window"><CatalogueImage imageKey={feature.imageKey}/></div>:<><span className="business-material" aria-hidden="true"/><span className="eyebrow">Catalogue reference</span><span className="business-category-pending">Image pending approval</span></>}</div><div><h3>{category.name}</h3><span className="text-link">Explore category <Arrow diagonal/></span></div></a>;}
function BusinessAbout(){return <>
 <header className="business-hero"><div><p className="eyebrow">Our business / Chandigarh, India</p><h1>ANUPAMA<br/><span>ENTERPRISES.</span></h1><p className="business-hero-model">Manufacturing & Trading</p><p className="business-lede">{company.introduction}</p><div className="business-actions"><a className="button" href="/products">Explore the catalogue <Arrow/></a><a className="text-link" href="/enquire">Discuss a requirement <Arrow diagonal/></a></div></div><figure className="business-hero-visual" data-tone="kraft"><span className="eyebrow">Paper. Packaging. Everyday essentials.</span><div className="media-window"><CatalogueImage imageKey="boxes" eager/></div><figcaption>Product imagery from the inherited catalogue.<br/>Owner approval required.</figcaption></figure></header>
 <section className="business-overview"><div><p className="eyebrow">The business at a glance</p><h2>A clear starting point<br/>for your requirement.</h2></div><div><p>ANUPAMA ENTERPRISES is owned by Laxman Tiwari and based in Chandigarh, India.</p><dl><div><dt>Business model</dt><dd>Manufacturing and Trading</dd></div><div><dt>Product focus</dt><dd>Paper bags, packaging products, office stationery and related products.</dd></div><div><dt>Location</dt><dd>Chandigarh, India</dd></div></dl><p className="business-note-small">The business model is confirmed at a general level. Which individual products are manufactured or traded requires owner confirmation.</p></div></section>
 <section className="business-range"><div className="business-section-heading"><div><p className="eyebrow">What we deal in</p><h2>Explore the product areas.</h2></div><p>The catalogue documents product references. Current range, availability and specifications require confirmation.</p></div><div className="business-category-grid">{categories.map(c=><BusinessCategory key={c.slug} category={c}/>)}</div><p className="business-note-small">Catalogue wording and source groups are retained. Images are temporary catalogue references requiring owner approval.</p></section>
 <section className="business-journey"><p className="eyebrow">How to work with us</p><h2>From a reference<br/>to a clear requirement.</h2><ol>{[['Explore','Browse the catalogue and choose a product reference.'],['Understand','Review the printed details, sizes and product information.'],['Prepare','Describe what you need in the enquiry preparation page.'],['Confirm','Confirm suitability, current availability and specifications with the business once contact channels are approved.']].map(([title,description],i)=><li key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol></section>
 <section className="business-cta"><p className="eyebrow">Start with what you need</p><h2>Have a requirement?</h2><p>Prepare the product reference and details you would like to discuss.</p><a className="button inverse" href="/enquire">Prepare an enquiry <Arrow diagonal/></a></section>
 </>;}
function EnquiryPage(){return <>
 <header className="enquiry-hero"><div><p className="eyebrow">Enquire / Chandigarh, India</p><h1>Start with<br/><span>what you need.</span></h1><p className="business-lede">Choose a product reference or describe your requirement. Prepare the details for a conversation with ANUPAMA ENTERPRISES.</p><p className="enquiry-notice">Contact channels awaiting confirmation. This page prepares a draft; it does not send enquiries.</p><a className="text-link" href="#enquiry-preparation">Prepare your requirement <Arrow/></a></div><figure className="enquiry-hero-visual" data-tone="sage"><div className="media-window"><CatalogueImage imageKey="protective" eager/></div><figcaption>Catalogue image · Owner approval required</figcaption></figure></header>
 <div className="enquiry-workspace"><EnquiryPreparation/><aside className="enquiry-contact-information"><p className="eyebrow">Contact & location</p><h2>Before we connect.</h2><p>Contact channels awaiting confirmation.</p><ul>{contacts.map(c=><li key={c.id}><span>{c.label}</span><span>Awaiting approval</span></li>)}</ul><dl><div><dt>Business</dt><dd>ANUPAMA ENTERPRISES</dd></div><div><dt>Location</dt><dd>Chandigarh, India</dd></div><div><dt>Business model</dt><dd>Manufacturing and Trading</dd></div></dl><p className="business-note-small">Current contact details, address, response times and product availability require owner confirmation. No message is delivered from this preview.</p><a className="text-link" href="/our-business">Our business <Arrow diagonal/></a></aside></div>
 </>;}
export default function BusinessPages({page}){useBusinessMetadata(page);return <div className="business-page" id="top"><a className="skip-link" href="#main-content">Skip to content</a><Navigation1 catalogue/><main id="main-content" className="container" tabIndex={-1}><nav className="business-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">{page==='business'?'Our Business':'Enquire'}</span></nav>{page==='business'?<BusinessAbout/>:<EnquiryPage/>}</main><Footer catalogue><TextHoverEffectDemo/></Footer></div>;}
