import React,{useRef,useState} from 'react';
import {products,productUrl} from '../catalogue/model.js';
import {Arrow} from '../components/Primitives.jsx';
import {limits,validateEnquiry} from './enquiryValidation.js';
export default function EnquiryPreparation(){
 const requested=new URLSearchParams(location.search).get('reference');
 const initial=products.find(p=>p.id===requested);
 const [values,setValues]=useState({name:'',company:'',email:'',phone:'',reference:initial?.id||'',requirement:'',message:''});
 const [errors,setErrors]=useState({}),[draft,setDraft]=useState(''),[copyStatus,setCopyStatus]=useState('');
 const form=useRef(null),result=useRef(null);
 const selected=products.find(p=>p.id===values.reference);
 function change(e){const {name,value}=e.target;setValues(v=>({...v,[name]:value}));setDraft('');setCopyStatus('');setErrors(old=>{const next={...old};delete next[name];return next;});}
 function prepare(e){e.preventDefault();const next=validateEnquiry(values);setErrors(next);setDraft('');setCopyStatus('');if(Object.keys(next).length){form.current.elements.namedItem(Object.keys(next)[0])?.focus();return;}const lines=['ENQUIRY DRAFT — NOT SENT','For ANUPAMA ENTERPRISES',`Name: ${values.name.trim()}`,values.company.trim()&&`Company: ${values.company.trim()}`,`Email: ${values.email.trim()}`,values.phone.trim()&&`Phone: ${values.phone.trim()}`,selected?`Product: ${selected.name}\nReference: ${selected.id} · Catalogue page ${selected.page}\nProduct page: ${new URL(productUrl(selected),location.origin).href}`:'Product: General requirement',`Requirement: ${values.requirement.trim()}`,values.message.trim()&&`Message: ${values.message.trim()}`,'Current availability and specifications require business confirmation.','Contact channels awaiting confirmation. This draft has not been sent.'];setDraft(lines.filter(Boolean).join('\n\n'));requestAnimationFrame(()=>result.current?.focus());}
 async function copy(){try{if(!navigator.clipboard?.writeText)throw new Error('unavailable');await navigator.clipboard.writeText(draft);setCopyStatus('Draft copied to your clipboard. It has not been sent.');}catch{setCopyStatus('Clipboard unavailable. Select the draft text and copy it manually.');result.current?.select();}}
 const field=(key,label,{type='text',required=false,area=false,autoComplete}={})=>{const id=`enquiry-${key}`,props={id,name:key,value:values[key],onChange:change,required,maxLength:limits[key],autoComplete,'aria-invalid':errors[key]?'true':undefined,'aria-describedby':errors[key]?`${id}-error`:undefined};return <div className={`enquiry-field ${area?'enquiry-field-wide':''}`}><label htmlFor={id}>{label}{required?' *':' (optional)'}</label>{area?<textarea {...props} rows={key==='requirement'?5:3}/>:<input {...props} type={type}/>}<div className="enquiry-field-meta">{errors[key]&&<p id={`${id}-error`} className="enquiry-field-error">{errors[key]}</p>}{area&&<span>{values[key].length} / {limits[key]}</span>}</div></div>;};
 return <section className="enquiry-preparation" id="enquiry-preparation"><p className="eyebrow">Your requirement</p><h2>Prepare an enquiry.</h2><p id="enquiry-form-note">Required fields are marked *. Your entries stay in this page’s memory and are cleared on reload. Nothing is sent or saved by the website.</p>{initial&&<p className="enquiry-context">From the catalogue: <strong>{initial.name}</strong> · {initial.id}</p>}{requested&&!initial&&<p className="enquiry-context">That catalogue reference could not be matched. Choose a reference below or prepare a general requirement.</p>}
 <form ref={form} noValidate onSubmit={prepare} aria-describedby="enquiry-form-note"><div className="enquiry-fields">{field('name','Name',{required:true,autoComplete:'name'})}{field('company','Company / business name',{autoComplete:'organization'})}{field('email','Email',{type:'email',required:true,autoComplete:'email'})}{field('phone','Phone',{type:'tel',autoComplete:'tel'})}<div className="enquiry-field enquiry-field-wide"><label htmlFor="enquiry-reference">Product / reference (optional)</label><select id="enquiry-reference" name="reference" value={values.reference} onChange={change}><option value="">General requirement</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.id}</option>)}</select>{selected&&<p className="enquiry-reference-link"><a href={productUrl(selected)}>View product details <Arrow diagonal/></a><span>Catalogue page {selected.page} · Current status requires confirmation</span></p>}</div>{field('requirement','Requirement',{area:true,required:true})}{field('message','Additional message',{area:true})}</div>{Object.keys(errors).length>0&&<p className="enquiry-errors-summary" role="alert">Please check the highlighted fields. Nothing has been sent.</p>}<div className="enquiry-form-actions"><button type="submit" className="button">Prepare enquiry draft <Arrow/></button><span>Preview only · No submission</span></div></form>
 {draft&&<div className="enquiry-draft"><p role="status" className="enquiry-draft-status">Draft prepared — not sent.</p><label htmlFor="enquiry-draft-text">Your enquiry draft</label><textarea id="enquiry-draft-text" ref={result} value={draft} readOnly rows={14} aria-describedby="enquiry-draft-note"/><p id="enquiry-draft-note">Review or copy this draft for later use. Approved contact channels are not available yet.</p><button className="button secondary" type="button" onClick={copy}>Copy draft</button><p role="status">{copyStatus}</p></div>}
 </section>;
}

