import {createServer} from 'vite';
import {writeFile} from 'node:fs/promises';
import {chromium} from 'file:///C:/Users/Jeswin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
// Isolated synthetic gallery fixture only; never included in the production entry.
await writeFile('tmp/homepage-qa/gallery-fixture.html','<div id="root"></div><script type="module" src="/tmp/homepage-qa/gallery-fixture.jsx"></script>');
await writeFile('tmp/homepage-qa/gallery-fixture.jsx',`import React from 'react';import{createRoot}from'react-dom/client';import Gallery from '/src/catalogue/ProductGallery.jsx';import '/src/styles.css';import '/src/campaign.css';import '/src/creative.css';import '/src/grid-composition.css';import '/src/catalogue/catalogue.css';createRoot(document.getElementById('root')).render(<div style={{maxWidth:600,margin:'auto'}}><Gallery product={{id:'TEST',name:'Gallery test fixture',page:14}} images={[{imageKey:'labels'},{imageKey:'boxes'}]}/></div>);`);
const server=await createServer({server:{host:'127.0.0.1',port:0},clearScreen:false});await server.listen();
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tmp/homepage-qa/gallery-fixture.html`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Next product image'}).click();await page.waitForFunction(()=>document.querySelector('.product-gallery-primary .product-transition').dataset.product==='boxes');await page.getByRole('button',{name:'View product image 2'}).focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.product-gallery-primary .product-transition').dataset.product==='labels');assert.equal(await page.getByRole('button',{name:'View product image 1'}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Previous product image'}).click();await page.waitForTimeout(1000);assert.equal(await page.locator('.product-gallery-primary .product-layer').count(),1);await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Next product image'}).click();await page.waitForTimeout(100);assert.equal(await page.locator('.product-gallery-primary .product-outgoing').count(),0);console.log('Synthetic multi-image gallery: next/previous, thumbnail selection, arrow-key wrap, cleanup and reduced motion passed');}finally{await browser.close();await server.close();}
