import {chromium} from 'file:///C:/Users/Jeswin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {validateEnquiry} from '../src/business/enquiryValidation.js';
const valid={name:'Visitor',company:'',email:'visitor@example.test',phone:'',requirement:'Packaging requirement',message:''};
assert.deepEqual(validateEnquiry(valid),{});
assert.ok(validateEnquiry({...valid,requirement:'x'.repeat(1501)}).requirement);
assert.ok(validateEnquiry({...valid,message:'x'.repeat(2001)}).message);
assert.ok(validateEnquiry({...valid,phone:'123'}).phone);
await mkdir('tmp/phase-4-qa',{recursive:true});
const origin='http://127.0.0.1:4173',widths=[375,390,768,1024,1440,1920],errors=[],external=[],mutations=[];
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{
 const context=await browser.newContext();await context.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__copiedDraft=text;}}});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:'))external.push(r.url());if(r.method()!=='GET')mutations.push({url:r.url(),method:r.method()});});
 for(const width of widths){await page.setViewportSize({width,height:1000});for(const path of ['/our-business','/enquire']){
  await page.goto(origin+path,{waitUntil:'networkidle'});assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'),origin+path);assert.match(await page.title(),/ANUPAMA ENTERPRISES/);assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex, nofollow');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.equal(await page.locator('[href^="tel:"],[href^="mailto:"],[href*="wa.me"]').count(),0);
  assert.equal(await page.locator('nav[aria-label=Footer] a').count(),4);assert.deepEqual(await page.locator('nav[aria-label=Footer] a').evaluateAll(a=>a.map(e=>e.getAttribute('href'))),['/','/products','/our-business','/enquire']);
  assert.equal(await page.locator('.brand-text-scene [data-wordmark-base]').textContent(),'ANUPAMA ENTERPRISES');
  const historical=/97791|82888|printnpacksolutionz|Makhan Majra|500\+|10\+ years|world.class|leading company/;assert.doesNotMatch(await page.locator('main').innerText(),historical);
  await page.evaluate(async()=>{await Promise.all([...document.images].filter(i=>i.loading!=='lazy').map(i=>i.decode().catch(()=>{})));});
  assert.equal(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.complete&&i.naturalWidth===0).length),0);
  if(path==='/our-business'){assert.match(await page.locator('main').innerText(),/Laxman Tiwari/);assert.equal(await page.locator('.business-category').count(),10);}else{assert.equal(await page.locator('form').count(),1);assert.equal(await page.locator('form label').count(),7);}
  if([375,1440].includes(width)){await page.screenshot({path:`tmp/phase-4-qa/${path.slice(1)}-${width}-full.png`,fullPage:true});await page.screenshot({path:`tmp/phase-4-qa/${path.slice(1)}-${width}-hero.png`});}
  if(width<960){const trigger=page.getByRole('button',{name:'Open navigation',exact:true});await trigger.click();const dialog=page.getByRole('dialog',{name:'Navigation',exact:true});await dialog.waitFor();for(let i=0;i<9;i++){await page.keyboard.press('Tab');assert.equal(await dialog.evaluate(d=>d.contains(document.activeElement)),true);}await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);await trigger.click();await dialog.getByRole('link',{name:path==='/enquire'?'Our business':'Enquire',exact:true}).click();await page.waitForURL(origin+(path==='/enquire'?'/our-business':'/enquire'));await page.locator('.business-page').waitFor();assert.equal(await page.evaluate(()=>document.body.style.overflow),'');}
 }}
 await page.goto(origin+'/products/plain-corrugated-boxes',{waitUntil:'networkidle'});await page.getByRole('link',{name:'Prepare an enquiry',exact:true}).click();await page.waitForURL('**/enquire?reference=CAT-006');await page.locator('#enquiry-reference').waitFor();assert.equal(await page.locator('#enquiry-reference').inputValue(),'CAT-006');assert.match(await page.locator('.enquiry-context').innerText(),/PLAIN CORRUGATED BOXES/);assert.equal(await page.locator('.enquiry-reference-link a').getAttribute('href'),'/products/plain-corrugated-boxes-cat-006');
 await page.getByRole('button',{name:'Prepare enquiry draft'}).click();assert.equal(await page.locator('[aria-invalid=true]').count(),3);assert.equal(await page.locator('#enquiry-name').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.enquiry-draft').count(),0);
 await page.locator('#enquiry-name').fill('QA Visitor');await page.locator('#enquiry-email').fill('invalid-email');await page.locator('#enquiry-phone').fill('abc');await page.locator('#enquiry-requirement').fill('Please confirm the catalogue box sizes.');await page.getByRole('button',{name:'Prepare enquiry draft'}).click();assert.equal(await page.locator('[aria-invalid=true]').count(),2);assert.match(await page.locator('#enquiry-email-error').innerText(),/valid email/);assert.match(await page.locator('#enquiry-phone-error').innerText(),/digits/);
 for(const [id,max] of [['requirement','1500'],['message','2000']])assert.equal(await page.locator('#enquiry-'+id).getAttribute('maxlength'),max);
 await page.locator('#enquiry-email').fill('qa@example.test');await page.locator('#enquiry-phone').fill('+91 98765 43210');await page.getByRole('button',{name:'Prepare enquiry draft'}).click();await page.locator('.enquiry-draft').waitFor();const draft=await page.locator('#enquiry-draft-text').inputValue();assert.match(draft,/ENQUIRY DRAFT — NOT SENT/);assert.match(draft,/PLAIN CORRUGATED BOXES/);assert.match(draft,/CAT-006/);assert.match(draft,/qa@example.test/);assert.equal(await page.locator('#enquiry-draft-text').evaluate(e=>e===document.activeElement),true);await page.getByRole('button',{name:'Copy draft',exact:true}).click();await page.waitForFunction(()=>!!window.__copiedDraft);assert.equal(await page.evaluate(()=>window.__copiedDraft),draft);
 await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw new Error('Clipboard unavailable');};});await page.getByRole('button',{name:'Copy draft',exact:true}).click();assert.match(await page.locator('.enquiry-draft').innerText(),/Clipboard unavailable/);
 await page.locator('#enquiry-message').fill('Changed requirement context');assert.equal(await page.locator('.enquiry-draft').count(),0);
 assert.equal(await page.evaluate(()=>localStorage.length),0);assert.equal(await page.evaluate(()=>sessionStorage.length),0);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#enquiry-name').inputValue(),'');assert.equal(await page.locator('#enquiry-reference').inputValue(),'CAT-006');
 await page.goto(origin+'/enquire?reference=INVALID',{waitUntil:'networkidle'});assert.equal(await page.locator('#enquiry-reference').inputValue(),'');assert.match(await page.locator('.enquiry-context').innerText(),/could not be matched/);
 await page.emulateMedia({reducedMotion:'reduce'});for(const path of ['/our-business','/enquire']){await page.goto(origin+path,{waitUntil:'networkidle'});assert.equal(await page.locator('header.business-hero > div,header.enquiry-hero > div').evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('.brand-text-scene').scrollIntoViewIfNeeded();await page.locator('.text-hover-effect').waitFor();assert.equal(await page.locator('[data-wordmark-base]').evaluate(e=>getComputedStyle(e).strokeDasharray),'none');assert.equal(await page.locator('[data-wordmark-enhancement]').count(),0);}
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});
 await page.goto(origin+'/our-business',{waitUntil:'networkidle'});await page.locator('nav[aria-label=Primary]').getByRole('link',{name:'Catalogue',exact:true}).click();await page.waitForURL(origin+'/products');await page.locator('h1').waitFor();await page.locator('nav[aria-label=Primary]').getByRole('link',{name:'Our business',exact:true}).click();await page.waitForURL(origin+'/our-business');await page.locator('h1').waitFor();await page.locator('.header-enquire').click();await page.waitForURL(origin+'/enquire');await page.locator('h1').waitFor();await page.locator('nav[aria-label=Footer]').getByRole('link',{name:'Home',exact:true}).click();await page.waitForURL(origin+'/');await page.locator('.hero').waitFor();
 const frozen=[];for(const [path,title] of [['/','Paper.\nPackaging.\nPossibilities.'],['/products','Explore the\ncatalogue.'],['/products/category/corrugated-boxes','Corrugated Boxes'],['/products/plain-corrugated-boxes','PLAIN CORRUGATED BOXES']]){await page.goto(origin+path,{waitUntil:'networkidle'});assert.equal((await page.locator('h1').innerText()).replace(/\s/g,''),title.replace(/\s/g,''));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.site-header .header-enquire').getAttribute('href'),'/enquire'+(path.includes('plain-corrugated')?'?reference=CAT-006':''));frozen.push({path,title:await page.locator('h1').innerText()});}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(mutations,[]);const report={status:'passed',widths,routes:['/our-business','/enquire'],frozen,checks:['metadata and refresh','truthful confirmed business identity','10 actual category links','product-aware reference prefill and invalid-reference recovery','required/email/phone validation and length limits','draft not sent; explicit copy only; edits invalidate stale draft','reload clears personal fields; no website storage','mobile focus trap/Escape/return and route navigation','static wordmark and reduced motion','four consistent footer links','no active historical contact channels','no overflow/broken images/console errors/external requests/POST'],errors};await writeFile('tmp/phase-4-qa/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}

