import React from 'react';
import {Arrow} from '../components/Primitives.jsx';
import CatalogueImage from '../components/CatalogueImage.jsx';
import {productUrl,categoryUrl} from './model.js';
export function Breadcrumb({category,product}){return <nav className="catalogue-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/products">Catalogue</a>{category&&<><span>/</span><a href={categoryUrl(category)}>{category.name}</a></>}{product&&<><span>/</span><span aria-current="page">{product.name}</span></>}</nav>;}
export function ProductMedia({product,eager=false}){return <div className="catalogue-media">{product.imageKey?<div className="media-window"><CatalogueImage imageKey={product.imageKey} eager={eager}/></div>:<div className="catalogue-no-image"><span className="eyebrow">Catalogue reference / {product.id}</span><p>Product image awaiting approval</p><small>PDF page {product.page}</small></div>}</div>;}
export function ProductCard({product,large=false}){return <article className={`catalogue-product ${large?'catalogue-product-large':''}`}><a className="catalogue-product-link" href={productUrl(product)}><ProductMedia product={product}/><div className="catalogue-product-copy"><p className="eyebrow">{product.category}</p><h3>{product.name} <Arrow diagonal/></h3><p className="catalogue-source">Catalogue page {product.page} · {product.id}</p><span className="text-link">View reference <Arrow/></span></div></a></article>;}
export function CategoryPanel({category,index}){return <a className={`catalogue-category ${index===0?'catalogue-category-lead':''}`} href={categoryUrl(category)}><div><p className="eyebrow">Product area / {String(index+1).padStart(2,'0')}</p><h2>{category.name}</h2><p>{category.count} catalogue {category.count===1?'reference':'references'}</p><Arrow diagonal/></div>{category.imageKey&&<div className="media-window"><CatalogueImage imageKey={category.imageKey}/></div>}</a>;}
export function EnquiryCTA({product}){return <section className="catalogue-enquiry" id="catalogue-enquire"><p className="eyebrow">Discuss a requirement</p><h2>{product?'Interested in this reference?':'Start with what you need.'}</h2>{product&&<p>{product.name} · {product.id}</p>}<p>Contact channels are awaiting owner confirmation. This preview does not send enquiries. Current availability and specifications require confirmation.</p><a className="text-link" href={product?`/enquire?reference=${encodeURIComponent(product.id)}`:"/enquire"}>Prepare an enquiry <Arrow diagonal/></a></section>;}

