import React from 'react';
import CatalogueImage from '../components/CatalogueImage.jsx';
import {Arrow} from '../components/Primitives.jsx';
import {categoryUrl,productUrl} from './model.js';
import {categoryTone} from './CategoryPresentation.jsx';

export function CatalogueHero(){return <header className="hub-hero"><div><p className="eyebrow">ANUPAMA ENTERPRISES / Catalogue</p><h1>Explore the<br/><span>catalogue.</span></h1><p className="hub-description">Paper, packaging and everyday essentials. Explore the product references documented in the inherited catalogue.</p><div className="hub-hero-actions"><a className="button" href="#category-explorer">Explore categories <Arrow/></a><a className="text-link" href="#catalogue-results">Find your product <Arrow diagonal/></a></div><p className="category-availability">57 catalogue references · Current availability unconfirmed</p></div><div className="hub-hero-composition"><div className="hub-hero-labels category-image-stage" data-tone="neutral"><div className="media-window"><CatalogueImage imageKey="labels" eager/></div><span className="hub-image-label">DIRECT THERMAL LABEL</span></div><div className="hub-hero-boxes category-image-stage" data-tone="kraft"><div className="media-window"><CatalogueImage imageKey="boxes" eager/></div></div><p className="hub-hero-caption">Inherited catalogue imagery<br/>Owner approval required</p></div></header>;}
export function VisualCategoryExplorer({categories}){return <section id="category-explorer" className="hub-explorer" aria-label="Catalogue categories"><div className="hub-section-title"><p className="eyebrow">Start with a product area</p><h2>Explore product categories.</h2><p>Source groups preserved as documented in the catalogue.</p></div><div className="hub-category-grid">{categories.map((c,i)=><a className={`catalogue-category hub-category ${c.imageKey?'hub-category-visual':'hub-category-type'} ${i===1?'hub-category-feature':''}`} key={c.slug} href={categoryUrl(c)} data-tone={categoryTone(c)}>{c.imageKey&&<div className="hub-category-stage"><div className="media-window"><CatalogueImage imageKey={c.imageKey}/></div></div>}<div className="hub-category-copy"><p className="eyebrow">{c.count} catalogue {c.count===1?'reference':'references'}</p><h3>{c.name}</h3><span className="text-link">Explore category <Arrow diagonal/></span></div></a>)}</div></section>;}
export function HubProductCard({product,large=false}){return <article className={`catalogue-product hub-product ${product.imageKey?'hub-product-photo':'hub-product-information'} ${large?'catalogue-product-large':''}`} data-tone={categoryTone(product.categorySlug)}><a className="catalogue-product-link" href={productUrl(product)}>{product.imageKey&&<div className="category-image-stage"><div className="media-window"><CatalogueImage imageKey={product.imageKey}/></div></div>}<div className="catalogue-product-copy"><p className="eyebrow">{product.category}</p><h3>{product.name}</h3>{product.variant&&<p className="hub-product-variant">{product.variant}</p>}<p className="hub-product-image-status">{product.imageKey?'Catalogue image · Owner approval required':'Image pending approval'}</p><span className="text-link">View product <Arrow/></span></div></a></article>;}
