import React from 'react';
import enrichment from '../generated/product-enrichment.json';
import {categories,products,productUrl,relatedProducts} from './model.js';
import {Breadcrumb,EnquiryCTA} from './Components.jsx';
import {Arrow} from '../components/Primitives.jsx';
import ProductGallery from './ProductGallery.jsx';
import CatalogueImage from '../components/CatalogueImage.jsx';
import {categoryTone} from './CategoryPresentation.jsx';

function RelatedVisual({product}){return <article className="catalogue-product detail-related-product" data-tone={categoryTone(product.categorySlug)}><a className="catalogue-product-link" href={productUrl(product)}><div className={`category-image-stage ${product.imageKey?'':'category-type-stage'}`}>{product.imageKey?<div className="media-window"><CatalogueImage imageKey={product.imageKey}/></div>:<><span className="category-material-lines" aria-hidden="true"/><span className="category-placeholder-title">{product.name}</span><span className="category-pending">Image pending approval</span></>}</div><div className="catalogue-product-copy"><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><span className="text-link">View product <Arrow/></span>{product.imageKey&&<p className="category-card-approval">Catalogue image · Owner approval required</p>}</div></a></article>;}

export default function ProductDetail({product}){
 const category=categories.find(c=>c.slug===product.categorySlug),related=relatedProducts(product);
 const record=enrichment.records[product.id],profile=enrichment.profiles[record?.profileId];
 const linked=(record?.linkedReferences||[]).map(id=>products.find(p=>p.id===id)).filter(Boolean);
 const fields=[['Variant / source wording',product.variant],['Sizes / dimensions as printed',record?.sizeReference?.value||product.size],['Specifications as printed',product.specification],['Material explicitly stated',product.material],['Customisation reference',product.customisation]].filter(([,v])=>v);
 const sources=profile?[...new Map(Object.values(profile.fields).map(f=>[f.sourceUrl,f])).values()]:[];
 const keyFields=[['Catalogue detail',product.specification],['Material',product.material],['Variant',product.variant],['Size reference',record?.sizeEntries?.[0]?.value||record?.sizeReference?.value||product.size],['Customisation',product.customisation]].filter(([,v])=>v).slice(0,3);
 return <div className="premium-product-detail"><Breadcrumb category={category} product={product}/>
 <div className="catalogue-detail enriched-detail"><ProductGallery key={product.id} product={product} images={record?.images}/><div className="product-detail-intro"><p className="eyebrow">{category.name}</p><h1>{product.name}</h1><p className="product-catalogue-summary">{record?.catalogueDescription?.value}</p><p className="catalogue-detail-status"><span className="detail-status-dot" aria-hidden="true"/>Current availability requires confirmation</p><div className="product-hero-details">{keyFields.length?<dl>{keyFields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>:<p>Details require confirmation</p>}</div><a className="button" href="#catalogue-enquire">Discuss this product <Arrow diagonal/></a><p className="catalogue-source">Catalogue reference · {product.id} · Page {product.page}</p>{/AMAZON|FLIPKART|FLIPAKRT|MYNTRA|MEESHO|SNAPDEAL|PAYTM/i.test(product.name)&&<p className="catalogue-source">Third-party names are inherited catalogue terminology. No endorsement, affiliation or partnership is implied.</p>}</div></div>
 {fields.length>0&&<section className="catalogue-specifications"><div className="detail-section-heading"><div><p className="eyebrow">From the catalogue</p><h2>Key details.</h2></div><p>Source wording preserved. Current specifications, dimension interpretation and suitability require business confirmation.</p></div><dl>{fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}
 {record?.sizeEntries?.length>0&&<section className="product-size-section"><div className="detail-section-heading"><div><p className="eyebrow">Anupama catalogue fact</p><h2>Available sizes.</h2></div><p>Catalogue entries as printed. Dimension interpretation requires confirmation.</p></div><table><caption>{product.name} — catalogue size references</caption><thead><tr><th scope="col">Source entry</th><th scope="col">Size / dimension / seal wording</th></tr></thead><tbody>{record.sizeEntries.map((entry,i)=><tr key={i}><th scope="row">{String(i+1).padStart(2,'0')}</th><td>{entry.value}</td></tr>)}</tbody></table></section>}
 {product.customisation&&<section className="product-customisation"><p className="eyebrow">Anupama catalogue fact</p><h2>Customisation reference.</h2><p>{product.customisation}</p><p>Only this source wording is confirmed by the catalogue. Current options and production capability require owner confirmation.</p></section>}
 {linked.length>0&&<section className="product-linked-references"><p className="eyebrow">Compare catalogue references</p><h2>Types & named options.</h2><p>Separate catalogue occurrences in the same general product context. This grouping does not establish interchangeable specifications or an owner-approved product family.</p><div>{linked.map(p=><a href={productUrl(p)} key={p.id}><span>{p.name}{p.name===product.name?` · Catalogue page ${p.page}`:''}</span><Arrow diagonal/></a>)}</div></section>}
 {profile&&<section className="product-external-reference"><div><p className="eyebrow">General product reference</p><h2>Understanding this product.</h2><p className="product-reference-warning">General industry information. This is not an Anupama product specification or a confirmed offering.</p></div><div className="detail-reference-accordions"><p className="detail-reference-type">{profile.title}</p><details><summary>What it is</summary><p className="product-reference-summary">{profile.fields.summary.value}</p><p>{profile.fields.description.value}</p></details>{profile.fields.terminology&&<details className="product-reference-note"><summary>Common terminology</summary><p>{profile.fields.terminology.value}</p></details>}{profile.fields.applications&&<details className="product-reference-note"><summary>Typical applications</summary><p>{profile.fields.applications.value}</p></details>}</div></section>}
 {related.length>0&&<section className="catalogue-related"><p className="eyebrow">From the same catalogue category</p><h2>Explore related products.</h2><div className="catalogue-product-list">{related.map(p=><RelatedVisual key={p.id} product={p}/>)}</div></section>}
 <EnquiryCTA product={product}/>
 <details className="detail-verification"><summary><span>Source & verification</span><span className="detail-verification-label">Catalogue evidence · Owner confirmation required</span></summary><div className="detail-verification-body"><p className="catalogue-source">{product.id} · Catalogue page {product.page} · Catalogue presence does not confirm current manufacture, trading or stock.</p>{product.requiresReview&&<p className="catalogue-review-note">Ambiguous catalogue specifications remain withheld pending business confirmation.</p>}{record?.researchWithheld&&<p className="catalogue-review-note">Further product information requires owner clarification. The catalogue wording is retained.</p>}<section className="product-confirmation"><p className="eyebrow">Owner confirmation required</p><h2>Confirm before choosing.</h2><p>Details require confirmation. The catalogue establishes presence, while current offering and suitability remain unverified.</p><ul>{record?.confirmationItems?.map(item=><li key={item.value}>{item.value}</li>)}</ul></section>{profile&&<details className="product-reference-sources"><summary>Product reference sources</summary><ul>{sources.map(s=><li key={s.sourceUrl}><a href={s.sourceUrl} target="_blank" rel="noopener noreferrer">{s.sourceTitle} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></li>)}</ul><p>Independent reference material; source product features are not attributed to ANUPAMA ENTERPRISES.</p></details>}</div></details>
 </div>;
}
